const NETWORK_COLLECTION_NAME = "mutual_aid_networks";
const FOOD_RESOURCE_COLLECTION_NAME = "food_resources";

module.exports = {
    NETWORK_COLLECTION_NAME: NETWORK_COLLECTION_NAME,
    FOOD_RESOURCE_COLLECTION_NAME: FOOD_RESOURCE_COLLECTION_NAME
}